# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz(object):
    def setupUi(self, quiz):
        quiz.setObjectName("quiz")
        quiz.resize(488, 245)
        self.verticalLayout = QtWidgets.QVBoxLayout(quiz)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.labelTitle = QtWidgets.QLabel(quiz)
        self.labelTitle.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_7.addWidget(self.labelTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelEnglish = QtWidgets.QLabel(quiz)
        self.labelEnglish.setFrameShape(QtWidgets.QFrame.Box)
        self.labelEnglish.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEnglish.setObjectName("labelEnglish")
        self.horizontalLayout.addWidget(self.labelEnglish)
        self.labelFrench = QtWidgets.QLabel(quiz)
        self.labelFrench.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFrench.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrench.setObjectName("labelFrench")
        self.horizontalLayout.addWidget(self.labelFrench)
        self.labelSpanish = QtWidgets.QLabel(quiz)
        self.labelSpanish.setFrameShape(QtWidgets.QFrame.Box)
        self.labelSpanish.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpanish.setObjectName("labelSpanish")
        self.horizontalLayout.addWidget(self.labelSpanish)
        self.labelGerman = QtWidgets.QLabel(quiz)
        self.labelGerman.setFrameShape(QtWidgets.QFrame.Box)
        self.labelGerman.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGerman.setObjectName("labelGerman")
        self.horizontalLayout.addWidget(self.labelGerman)
        self.labelJapanese = QtWidgets.QLabel(quiz)
        self.labelJapanese.setFrameShape(QtWidgets.QFrame.Box)
        self.labelJapanese.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJapanese.setObjectName("labelJapanese")
        self.horizontalLayout.addWidget(self.labelJapanese)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEN1 = QtWidgets.QLabel(quiz)
        self.labelEN1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEN1.setObjectName("labelEN1")
        self.horizontalLayout_2.addWidget(self.labelEN1)
        self.lineAnswer1 = QtWidgets.QLineEdit(quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAnswer1.sizePolicy().hasHeightForWidth())
        self.lineAnswer1.setSizePolicy(sizePolicy)
        self.lineAnswer1.setObjectName("lineAnswer1")
        self.horizontalLayout_2.addWidget(self.lineAnswer1)
        self.labelES1 = QtWidgets.QLabel(quiz)
        self.labelES1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelES1.setObjectName("labelES1")
        self.horizontalLayout_2.addWidget(self.labelES1)
        self.labelGER1 = QtWidgets.QLabel(quiz)
        self.labelGER1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGER1.setObjectName("labelGER1")
        self.horizontalLayout_2.addWidget(self.labelGER1)
        self.labelJAP1 = QtWidgets.QLabel(quiz)
        self.labelJAP1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJAP1.setObjectName("labelJAP1")
        self.horizontalLayout_2.addWidget(self.labelJAP1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelEN2 = QtWidgets.QLabel(quiz)
        self.labelEN2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEN2.setObjectName("labelEN2")
        self.horizontalLayout_3.addWidget(self.labelEN2)
        self.labelFR2 = QtWidgets.QLabel(quiz)
        self.labelFR2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFR2.setObjectName("labelFR2")
        self.horizontalLayout_3.addWidget(self.labelFR2)
        self.labelES2 = QtWidgets.QLabel(quiz)
        self.labelES2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelES2.setObjectName("labelES2")
        self.horizontalLayout_3.addWidget(self.labelES2)
        self.labelGER2 = QtWidgets.QLabel(quiz)
        self.labelGER2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGER2.setObjectName("labelGER2")
        self.horizontalLayout_3.addWidget(self.labelGER2)
        self.lineAnswer2 = QtWidgets.QLineEdit(quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAnswer2.sizePolicy().hasHeightForWidth())
        self.lineAnswer2.setSizePolicy(sizePolicy)
        self.lineAnswer2.setObjectName("lineAnswer2")
        self.horizontalLayout_3.addWidget(self.lineAnswer2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineAnswer3 = QtWidgets.QLineEdit(quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAnswer3.sizePolicy().hasHeightForWidth())
        self.lineAnswer3.setSizePolicy(sizePolicy)
        self.lineAnswer3.setObjectName("lineAnswer3")
        self.horizontalLayout_4.addWidget(self.lineAnswer3)
        self.labelFR3 = QtWidgets.QLabel(quiz)
        self.labelFR3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFR3.setObjectName("labelFR3")
        self.horizontalLayout_4.addWidget(self.labelFR3)
        self.labelES3 = QtWidgets.QLabel(quiz)
        self.labelES3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelES3.setObjectName("labelES3")
        self.horizontalLayout_4.addWidget(self.labelES3)
        self.labelGER3 = QtWidgets.QLabel(quiz)
        self.labelGER3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGER3.setObjectName("labelGER3")
        self.horizontalLayout_4.addWidget(self.labelGER3)
        self.labelJAP3 = QtWidgets.QLabel(quiz)
        self.labelJAP3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJAP3.setObjectName("labelJAP3")
        self.horizontalLayout_4.addWidget(self.labelJAP3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelEN4 = QtWidgets.QLabel(quiz)
        self.labelEN4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEN4.setObjectName("labelEN4")
        self.horizontalLayout_5.addWidget(self.labelEN4)
        self.labelFR4 = QtWidgets.QLabel(quiz)
        self.labelFR4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFR4.setObjectName("labelFR4")
        self.horizontalLayout_5.addWidget(self.labelFR4)
        self.lineAnswer4 = QtWidgets.QLineEdit(quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAnswer4.sizePolicy().hasHeightForWidth())
        self.lineAnswer4.setSizePolicy(sizePolicy)
        self.lineAnswer4.setObjectName("lineAnswer4")
        self.horizontalLayout_5.addWidget(self.lineAnswer4)
        self.labelGER4 = QtWidgets.QLabel(quiz)
        self.labelGER4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGER4.setObjectName("labelGER4")
        self.horizontalLayout_5.addWidget(self.labelGER4)
        self.labelJAP4 = QtWidgets.QLabel(quiz)
        self.labelJAP4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJAP4.setObjectName("labelJAP4")
        self.horizontalLayout_5.addWidget(self.labelJAP4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelEN5 = QtWidgets.QLabel(quiz)
        self.labelEN5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEN5.setObjectName("labelEN5")
        self.horizontalLayout_6.addWidget(self.labelEN5)
        self.labelFR5 = QtWidgets.QLabel(quiz)
        self.labelFR5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFR5.setObjectName("labelFR5")
        self.horizontalLayout_6.addWidget(self.labelFR5)
        self.labelES5 = QtWidgets.QLabel(quiz)
        self.labelES5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelES5.setObjectName("labelES5")
        self.horizontalLayout_6.addWidget(self.labelES5)
        self.lineAnswer5 = QtWidgets.QLineEdit(quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAnswer5.sizePolicy().hasHeightForWidth())
        self.lineAnswer5.setSizePolicy(sizePolicy)
        self.lineAnswer5.setObjectName("lineAnswer5")
        self.horizontalLayout_6.addWidget(self.lineAnswer5)
        self.labelJAP5 = QtWidgets.QLabel(quiz)
        self.labelJAP5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJAP5.setObjectName("labelJAP5")
        self.horizontalLayout_6.addWidget(self.labelJAP5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(quiz)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(quiz)
        self.buttonBox.accepted.connect(quiz.accept)
        self.buttonBox.rejected.connect(quiz.reject)
        QtCore.QMetaObject.connectSlotsByName(quiz)

    def retranslateUi(self, quiz):
        _translate = QtCore.QCoreApplication.translate
        quiz.setWindowTitle(_translate("quiz", "Dialog"))
        self.labelTitle.setText(_translate("quiz", "       QUIZ : Fill in the blanks with the correct words.       "))
        self.labelEnglish.setText(_translate("quiz", "English"))
        self.labelFrench.setText(_translate("quiz", "French"))
        self.labelSpanish.setText(_translate("quiz", "Spanish"))
        self.labelGerman.setText(_translate("quiz", "German"))
        self.labelJapanese.setText(_translate("quiz", "Japanese"))
        self.labelEN1.setText(_translate("quiz", "TextLabel"))
        self.labelES1.setText(_translate("quiz", "TextLabel"))
        self.labelGER1.setText(_translate("quiz", "TextLabel"))
        self.labelJAP1.setText(_translate("quiz", "TextLabel"))
        self.labelEN2.setText(_translate("quiz", "TextLabel"))
        self.labelFR2.setText(_translate("quiz", "TextLabel"))
        self.labelES2.setText(_translate("quiz", "TextLabel"))
        self.labelGER2.setText(_translate("quiz", "TextLabel"))
        self.labelFR3.setText(_translate("quiz", "TextLabel"))
        self.labelES3.setText(_translate("quiz", "TextLabel"))
        self.labelGER3.setText(_translate("quiz", "TextLabel"))
        self.labelJAP3.setText(_translate("quiz", "TextLabel"))
        self.labelEN4.setText(_translate("quiz", "TextLabel"))
        self.labelFR4.setText(_translate("quiz", "TextLabel"))
        self.labelGER4.setText(_translate("quiz", "TextLabel"))
        self.labelJAP4.setText(_translate("quiz", "TextLabel"))
        self.labelEN5.setText(_translate("quiz", "TextLabel"))
        self.labelFR5.setText(_translate("quiz", "TextLabel"))
        self.labelES5.setText(_translate("quiz", "TextLabel"))
        self.labelJAP5.setText(_translate("quiz", "TextLabel"))
